module.exports = {
  screen: 'quiet-room.screen',
  header: 'quiet-room.header',
  profileButton: 'quiet-room.profile.open',
  profileMenu: 'quiet-room.profile.menu',
  profileLogoutButton: 'quiet-room.profile.logout',
  profileDeleteButton: 'quiet-room.profile.delete',
  profileSignInButton: 'quiet-room.profile.signin',
  aiConsentModal: 'quiet-room.ai-consent.modal',
  aiConsentCancelButton: 'quiet-room.ai-consent.cancel',
  aiConsentAcceptButton: 'quiet-room.ai-consent.accept',
  deleteAccountModal: 'quiet-room.delete-account.modal',
  deleteAccountCancelButton: 'quiet-room.delete-account.cancel',
  deleteAccountConfirmButton: 'quiet-room.delete-account.confirm',
  deleteAccountError: 'quiet-room.delete-account.error',
  messageList: 'quiet-room.messages.list',
  openingMessage: 'quiet-room.message.opening',
  composerInput: 'quiet-room.composer.input',
  composerExpand: 'quiet-room.composer.expand',
  composerFullscreenInput: 'quiet-room.composer.fullscreen.input',
  modelMenuButton: 'quiet-room.model.toggle',
  voiceModeIndicator: 'quiet-room.voice-mode.indicator',
  sendButton: 'quiet-room.send',
  fullscreenSendButton: 'quiet-room.send.fullscreen',
  scrollTopButton: 'quiet-room.scroll.top',
  scrollNewestButton: 'quiet-room.scroll.newest',
  promptCuesToggle: 'quiet-room.prompt-cues.toggle',
  modelMenu: 'quiet-room.model.menu',
  modelMenuVoiceToggle: 'quiet-room.model.voice-toggle',
  conversationsButton: 'quiet-room.conversations.open',
  conversationsPanel: 'quiet-room.conversations.panel',
  conversationsClose: 'quiet-room.conversations.close',
  conversationsList: 'quiet-room.conversations.list',
  conversationsNew: 'quiet-room.conversations.new',
  conversationsLoadingMore: 'quiet-room.conversations.loading-more',
  crucifixButton: 'quiet-room.crucifix.open',
  crucifixModal: 'quiet-room.crucifix.modal',
  crucifixClose: 'quiet-room.crucifix.close',
  crucifixImage: 'quiet-room.crucifix.image',
  loginModal: 'quiet-room.login.modal',
  loginAppleButton: 'quiet-room.login.apple',
  loginGoogleButton: 'quiet-room.login.google',
  loginEmailInput: 'quiet-room.login.email',
  loginPasswordInput: 'quiet-room.login.password',
  loginError: 'quiet-room.login.error',
  loginSigninButton: 'quiet-room.login.signin',
  thinkingRow: 'quiet-room.messages.thinking',
  message: {
    user(index) {
      return `quiet-room.message.user.${index}`;
    },
    assistant(index) {
      return `quiet-room.message.assistant.${index}`;
    },
    voice(role, index) {
      return `quiet-room.message.${role}.${index}.voice`;
    },
  },
};
